### ISSUE TITLE
Corrupt pbm files?

### ISSUE THREAD

**Issue by gitout** [miguelgrinberg/micropython-iot-tutorial#1]
Hello, 
While working in chapter 6, I found temperature.pbm and percent.pbm are corrupt and do not display a download option as shown below. 

![image](https://user-images.githubusercontent.com/4975143/236073462-ad941702-87c9-4022-b9b8-c9251f43f831.png)

**Comment by miguelgrinberg** [comment]
What makes you think the files are corrupted? The contents of line 4? These are images, they have binary data in them so strange characters are not an indication of problems. I actually see a download button when I look at this file.

![SCR-20230504-ekn](https://user-images.githubusercontent.com/2715854/236166925-731842f7-774b-4f88-bffd-f4b5c5b27b80.png)

**Comment by gitout** [comment]
Thank you, I was not seeing the download button because I was not properly logged in.  I was initially thrown off because clicking on the other pbm images would not show the contents of the file.  


![image](https://user-images.githubusercontent.com/4975143/236276365-09939e70-f656-4ca2-9f1b-fe5db7d012e5.png)
